services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - ollama-docker
# Uncomment the below if you have a GPU
###################################
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
###################################
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

networks:
  ollama-docker:
    external: false

volumes:
  ollama: {}
  mongo: {}
